# Generated by Django 4.0.2 on 2022-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_alter_extra_field_options_remove_candidate_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='extra_field',
            name='validation',
        ),
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extra_field',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
