# Generated by Django 4.0.2 on 2022-06-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_remove_candidate_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra_field',
            options={'verbose_name_plural': 'Zone_No_Edit'},
        ),
    ]
