# Generated by Django 4.0.2 on 2022-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_alter_extra_field_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Students_Voted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Total Students Voted',
            },
        ),
    ]
