# Generated by Django 4.0.2 on 2022-06-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0008_mock_alter_voted_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock_Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('priority', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Table Mock Position',
            },
        ),
        migrations.AlterModelOptions(
            name='mock',
            options={'verbose_name_plural': 'Table Mock Poll'},
        ),
        migrations.AlterField(
            model_name='mock',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.mock_positions'),
        ),
    ]
