# Generated by Django 4.0.2 on 2022-06-18 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0009_mock_positions_alter_mock_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voted',
            old_name='Total_Students_Voted',
            new_name='Voted',
        ),
        migrations.AddField(
            model_name='voted',
            name='Donot_edit_this_field',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mock',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='mock_positions',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
