# Generated by Django 4.0.2 on 2022-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0010_rename_total_students_voted_voted_voted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock_positions',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
