# Generated by Django 4.0.2 on 2022-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0011_alter_mock_positions_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voted',
            old_name='Voted',
            new_name='voted',
        ),
        migrations.AlterField(
            model_name='voted',
            name='Donot_edit_this_field',
            field=models.CharField(max_length=50),
        ),
    ]
