# Generated by Django 4.0.4 on 2022-07-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0014_po_vote_showing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='po_vote_showing',
            options={'verbose_name_plural': 'Po_stauts_results'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AddField(
            model_name='po_vote_showing',
            name='final_status',
            field=models.BooleanField(default=False),
        ),
    ]
